/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMobileDashboardRouteImport } from './routes/_authenticated/mobile-dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedTanksRouteRouteImport } from './routes/_authenticated/tanks/route'
import { Route as AuthenticatedSpbuRouteRouteImport } from './routes/_authenticated/spbu/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSalesRouteRouteImport } from './routes/_authenticated/sales/route'
import { Route as AuthenticatedReportsRouteRouteImport } from './routes/_authenticated/reports/route'
import { Route as AuthenticatedPricesRouteRouteImport } from './routes/_authenticated/prices/route'
import { Route as AuthenticatedPredictionRouteRouteImport } from './routes/_authenticated/prediction/route'
import { Route as AuthenticatedDepositsRouteRouteImport } from './routes/_authenticated/deposits/route'
import { Route as AuthenticatedDeliveriesRouteRouteImport } from './routes/_authenticated/deliveries/route'
import { Route as AuthenticatedAuditRouteRouteImport } from './routes/_authenticated/audit/route'
import { Route as AuthenticatedAdjustmentsRouteRouteImport } from './routes/_authenticated/adjustments/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSpbuIndexRouteImport } from './routes/_authenticated/spbu/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPricesIndexRouteImport } from './routes/_authenticated/prices/index'
import { Route as AuthenticatedPredictionIndexRouteImport } from './routes/_authenticated/prediction/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDepositsIndexRouteImport } from './routes/_authenticated/deposits/index'
import { Route as AuthenticatedDeliveriesIndexRouteImport } from './routes/_authenticated/deliveries/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAdjustmentsIndexRouteImport } from './routes/_authenticated/adjustments/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedReportsAllRouteImport } from './routes/_authenticated/reports/all'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDeliveriesConfirmRouteImport } from './routes/_authenticated/deliveries/confirm'
import { Route as AuthenticatedUsersCreateRouteRouteImport } from './routes/_authenticated/users/create/route'
import { Route as AuthenticatedReportsSalesRouteRouteImport } from './routes/_authenticated/reports/sales/route'
import { Route as AuthenticatedReportsLedgerRouteRouteImport } from './routes/_authenticated/reports/ledger/route'
import { Route as AuthenticatedReportsDepositsRouteRouteImport } from './routes/_authenticated/reports/deposits/route'
import { Route as AuthenticatedReportsDeliveriesRouteRouteImport } from './routes/_authenticated/reports/deliveries/route'
import { Route as AuthenticatedReportsAttendanceRouteRouteImport } from './routes/_authenticated/reports/attendance/route'
import { Route as AuthenticatedReportsAdjustmentRouteRouteImport } from './routes/_authenticated/reports/adjustment/route'
import { Route as AuthenticatedPredictionSalesRouteRouteImport } from './routes/_authenticated/prediction/sales/route'
import { Route as AuthenticatedPredictionDemandRouteRouteImport } from './routes/_authenticated/prediction/demand/route'
import { Route as AuthenticatedPredictionDeliveriesRouteRouteImport } from './routes/_authenticated/prediction/deliveries/route'
import { Route as AuthenticatedUsersCreateIndexRouteImport } from './routes/_authenticated/users/create/index'
import { Route as AuthenticatedReportsSalesIndexRouteImport } from './routes/_authenticated/reports/sales/index'
import { Route as AuthenticatedReportsLedgerIndexRouteImport } from './routes/_authenticated/reports/ledger/index'
import { Route as AuthenticatedReportsDepositsIndexRouteImport } from './routes/_authenticated/reports/deposits/index'
import { Route as AuthenticatedReportsDeliveriesIndexRouteImport } from './routes/_authenticated/reports/deliveries/index'
import { Route as AuthenticatedReportsAttendanceIndexRouteImport } from './routes/_authenticated/reports/attendance/index'
import { Route as AuthenticatedReportsAllIndexRouteImport } from './routes/_authenticated/reports/all/index'
import { Route as AuthenticatedReportsAdjustmentIndexRouteImport } from './routes/_authenticated/reports/adjustment/index'
import { Route as AuthenticatedPredictionSalesIndexRouteImport } from './routes/_authenticated/prediction/sales/index'
import { Route as AuthenticatedPredictionDemandIndexRouteImport } from './routes/_authenticated/prediction/demand/index'
import { Route as AuthenticatedPredictionDeliveriesIndexRouteImport } from './routes/_authenticated/prediction/deliveries/index'
import { Route as AuthenticatedDeliveriesConfirmIndexRouteImport } from './routes/_authenticated/deliveries/confirm/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMobileDashboardRoute =
  AuthenticatedMobileDashboardRouteImport.update({
    id: '/mobile-dashboard',
    path: '/mobile-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTanksRouteRoute = AuthenticatedTanksRouteRouteImport.update({
  id: '/tanks',
  path: '/tanks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpbuRouteRoute = AuthenticatedSpbuRouteRouteImport.update({
  id: '/spbu',
  path: '/spbu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesRouteRoute = AuthenticatedSalesRouteRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRouteRoute =
  AuthenticatedReportsRouteRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPricesRouteRoute =
  AuthenticatedPricesRouteRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPredictionRouteRoute =
  AuthenticatedPredictionRouteRouteImport.update({
    id: '/prediction',
    path: '/prediction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositsRouteRoute =
  AuthenticatedDepositsRouteRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveriesRouteRoute =
  AuthenticatedDeliveriesRouteRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRouteRoute = AuthenticatedAuditRouteRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdjustmentsRouteRoute =
  AuthenticatedAdjustmentsRouteRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpbuIndexRoute = AuthenticatedSpbuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSpbuRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSalesRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedPricesIndexRoute =
  AuthenticatedPricesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPricesRouteRoute,
  } as any)
const AuthenticatedPredictionIndexRoute =
  AuthenticatedPredictionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPredictionRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositsIndexRoute =
  AuthenticatedDepositsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDepositsRouteRoute,
  } as any)
const AuthenticatedDeliveriesIndexRoute =
  AuthenticatedDeliveriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeliveriesRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAuditRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdjustmentsIndexRoute =
  AuthenticatedAdjustmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdjustmentsRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsAllRoute = AuthenticatedReportsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthenticatedReportsRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveriesConfirmRoute =
  AuthenticatedDeliveriesConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => AuthenticatedDeliveriesRouteRoute,
  } as any)
const AuthenticatedUsersCreateRouteRoute =
  AuthenticatedUsersCreateRouteRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedUsersRouteRoute,
  } as any)
const AuthenticatedReportsSalesRouteRoute =
  AuthenticatedReportsSalesRouteRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedReportsLedgerRouteRoute =
  AuthenticatedReportsLedgerRouteRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedReportsDepositsRouteRoute =
  AuthenticatedReportsDepositsRouteRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedReportsDeliveriesRouteRoute =
  AuthenticatedReportsDeliveriesRouteRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedReportsAttendanceRouteRoute =
  AuthenticatedReportsAttendanceRouteRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedReportsAdjustmentRouteRoute =
  AuthenticatedReportsAdjustmentRouteRouteImport.update({
    id: '/adjustment',
    path: '/adjustment',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedPredictionSalesRouteRoute =
  AuthenticatedPredictionSalesRouteRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedPredictionRouteRoute,
  } as any)
const AuthenticatedPredictionDemandRouteRoute =
  AuthenticatedPredictionDemandRouteRouteImport.update({
    id: '/demand',
    path: '/demand',
    getParentRoute: () => AuthenticatedPredictionRouteRoute,
  } as any)
const AuthenticatedPredictionDeliveriesRouteRoute =
  AuthenticatedPredictionDeliveriesRouteRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedPredictionRouteRoute,
  } as any)
const AuthenticatedUsersCreateIndexRoute =
  AuthenticatedUsersCreateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsersCreateRouteRoute,
  } as any)
const AuthenticatedReportsSalesIndexRoute =
  AuthenticatedReportsSalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsSalesRouteRoute,
  } as any)
const AuthenticatedReportsLedgerIndexRoute =
  AuthenticatedReportsLedgerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsLedgerRouteRoute,
  } as any)
const AuthenticatedReportsDepositsIndexRoute =
  AuthenticatedReportsDepositsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsDepositsRouteRoute,
  } as any)
const AuthenticatedReportsDeliveriesIndexRoute =
  AuthenticatedReportsDeliveriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsDeliveriesRouteRoute,
  } as any)
const AuthenticatedReportsAttendanceIndexRoute =
  AuthenticatedReportsAttendanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsAttendanceRouteRoute,
  } as any)
const AuthenticatedReportsAllIndexRoute =
  AuthenticatedReportsAllIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsAllRoute,
  } as any)
const AuthenticatedReportsAdjustmentIndexRoute =
  AuthenticatedReportsAdjustmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsAdjustmentRouteRoute,
  } as any)
const AuthenticatedPredictionSalesIndexRoute =
  AuthenticatedPredictionSalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPredictionSalesRouteRoute,
  } as any)
const AuthenticatedPredictionDemandIndexRoute =
  AuthenticatedPredictionDemandIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPredictionDemandRouteRoute,
  } as any)
const AuthenticatedPredictionDeliveriesIndexRoute =
  AuthenticatedPredictionDeliveriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPredictionDeliveriesRouteRoute,
  } as any)
const AuthenticatedDeliveriesConfirmIndexRoute =
  AuthenticatedDeliveriesConfirmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeliveriesConfirmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/adjustments': typeof AuthenticatedAdjustmentsRouteRouteWithChildren
  '/audit': typeof AuthenticatedAuditRouteRouteWithChildren
  '/deliveries': typeof AuthenticatedDeliveriesRouteRouteWithChildren
  '/deposits': typeof AuthenticatedDepositsRouteRouteWithChildren
  '/prediction': typeof AuthenticatedPredictionRouteRouteWithChildren
  '/prices': typeof AuthenticatedPricesRouteRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteRouteWithChildren
  '/sales': typeof AuthenticatedSalesRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/spbu': typeof AuthenticatedSpbuRouteRouteWithChildren
  '/tanks': typeof AuthenticatedTanksRouteRoute
  '/users': typeof AuthenticatedUsersRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/mobile-dashboard': typeof AuthenticatedMobileDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/prediction/deliveries': typeof AuthenticatedPredictionDeliveriesRouteRouteWithChildren
  '/prediction/demand': typeof AuthenticatedPredictionDemandRouteRouteWithChildren
  '/prediction/sales': typeof AuthenticatedPredictionSalesRouteRouteWithChildren
  '/reports/adjustment': typeof AuthenticatedReportsAdjustmentRouteRouteWithChildren
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRouteRouteWithChildren
  '/reports/deliveries': typeof AuthenticatedReportsDeliveriesRouteRouteWithChildren
  '/reports/deposits': typeof AuthenticatedReportsDepositsRouteRouteWithChildren
  '/reports/ledger': typeof AuthenticatedReportsLedgerRouteRouteWithChildren
  '/reports/sales': typeof AuthenticatedReportsSalesRouteRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRouteRouteWithChildren
  '/deliveries/confirm': typeof AuthenticatedDeliveriesConfirmRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/reports/all': typeof AuthenticatedReportsAllRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/adjustments/': typeof AuthenticatedAdjustmentsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/deliveries/': typeof AuthenticatedDeliveriesIndexRoute
  '/deposits/': typeof AuthenticatedDepositsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/prediction/': typeof AuthenticatedPredictionIndexRoute
  '/prices/': typeof AuthenticatedPricesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/spbu/': typeof AuthenticatedSpbuIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/deliveries/confirm/': typeof AuthenticatedDeliveriesConfirmIndexRoute
  '/prediction/deliveries/': typeof AuthenticatedPredictionDeliveriesIndexRoute
  '/prediction/demand/': typeof AuthenticatedPredictionDemandIndexRoute
  '/prediction/sales/': typeof AuthenticatedPredictionSalesIndexRoute
  '/reports/adjustment/': typeof AuthenticatedReportsAdjustmentIndexRoute
  '/reports/all/': typeof AuthenticatedReportsAllIndexRoute
  '/reports/attendance/': typeof AuthenticatedReportsAttendanceIndexRoute
  '/reports/deliveries/': typeof AuthenticatedReportsDeliveriesIndexRoute
  '/reports/deposits/': typeof AuthenticatedReportsDepositsIndexRoute
  '/reports/ledger/': typeof AuthenticatedReportsLedgerIndexRoute
  '/reports/sales/': typeof AuthenticatedReportsSalesIndexRoute
  '/users/create/': typeof AuthenticatedUsersCreateIndexRoute
}
export interface FileRoutesByTo {
  '/tanks': typeof AuthenticatedTanksRouteRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/mobile-dashboard': typeof AuthenticatedMobileDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/adjustments': typeof AuthenticatedAdjustmentsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/deliveries': typeof AuthenticatedDeliveriesIndexRoute
  '/deposits': typeof AuthenticatedDepositsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/prediction': typeof AuthenticatedPredictionIndexRoute
  '/prices': typeof AuthenticatedPricesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/spbu': typeof AuthenticatedSpbuIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/deliveries/confirm': typeof AuthenticatedDeliveriesConfirmIndexRoute
  '/prediction/deliveries': typeof AuthenticatedPredictionDeliveriesIndexRoute
  '/prediction/demand': typeof AuthenticatedPredictionDemandIndexRoute
  '/prediction/sales': typeof AuthenticatedPredictionSalesIndexRoute
  '/reports/adjustment': typeof AuthenticatedReportsAdjustmentIndexRoute
  '/reports/all': typeof AuthenticatedReportsAllIndexRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceIndexRoute
  '/reports/deliveries': typeof AuthenticatedReportsDeliveriesIndexRoute
  '/reports/deposits': typeof AuthenticatedReportsDepositsIndexRoute
  '/reports/ledger': typeof AuthenticatedReportsLedgerIndexRoute
  '/reports/sales': typeof AuthenticatedReportsSalesIndexRoute
  '/users/create': typeof AuthenticatedUsersCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/adjustments': typeof AuthenticatedAdjustmentsRouteRouteWithChildren
  '/_authenticated/audit': typeof AuthenticatedAuditRouteRouteWithChildren
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRouteRouteWithChildren
  '/_authenticated/deposits': typeof AuthenticatedDepositsRouteRouteWithChildren
  '/_authenticated/prediction': typeof AuthenticatedPredictionRouteRouteWithChildren
  '/_authenticated/prices': typeof AuthenticatedPricesRouteRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteRouteWithChildren
  '/_authenticated/sales': typeof AuthenticatedSalesRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/spbu': typeof AuthenticatedSpbuRouteRouteWithChildren
  '/_authenticated/tanks': typeof AuthenticatedTanksRouteRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/mobile-dashboard': typeof AuthenticatedMobileDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/prediction/deliveries': typeof AuthenticatedPredictionDeliveriesRouteRouteWithChildren
  '/_authenticated/prediction/demand': typeof AuthenticatedPredictionDemandRouteRouteWithChildren
  '/_authenticated/prediction/sales': typeof AuthenticatedPredictionSalesRouteRouteWithChildren
  '/_authenticated/reports/adjustment': typeof AuthenticatedReportsAdjustmentRouteRouteWithChildren
  '/_authenticated/reports/attendance': typeof AuthenticatedReportsAttendanceRouteRouteWithChildren
  '/_authenticated/reports/deliveries': typeof AuthenticatedReportsDeliveriesRouteRouteWithChildren
  '/_authenticated/reports/deposits': typeof AuthenticatedReportsDepositsRouteRouteWithChildren
  '/_authenticated/reports/ledger': typeof AuthenticatedReportsLedgerRouteRouteWithChildren
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRouteRouteWithChildren
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRouteRouteWithChildren
  '/_authenticated/deliveries/confirm': typeof AuthenticatedDeliveriesConfirmRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/reports/all': typeof AuthenticatedReportsAllRouteWithChildren
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/adjustments/': typeof AuthenticatedAdjustmentsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/deliveries/': typeof AuthenticatedDeliveriesIndexRoute
  '/_authenticated/deposits/': typeof AuthenticatedDepositsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/prediction/': typeof AuthenticatedPredictionIndexRoute
  '/_authenticated/prices/': typeof AuthenticatedPricesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/spbu/': typeof AuthenticatedSpbuIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/deliveries/confirm/': typeof AuthenticatedDeliveriesConfirmIndexRoute
  '/_authenticated/prediction/deliveries/': typeof AuthenticatedPredictionDeliveriesIndexRoute
  '/_authenticated/prediction/demand/': typeof AuthenticatedPredictionDemandIndexRoute
  '/_authenticated/prediction/sales/': typeof AuthenticatedPredictionSalesIndexRoute
  '/_authenticated/reports/adjustment/': typeof AuthenticatedReportsAdjustmentIndexRoute
  '/_authenticated/reports/all/': typeof AuthenticatedReportsAllIndexRoute
  '/_authenticated/reports/attendance/': typeof AuthenticatedReportsAttendanceIndexRoute
  '/_authenticated/reports/deliveries/': typeof AuthenticatedReportsDeliveriesIndexRoute
  '/_authenticated/reports/deposits/': typeof AuthenticatedReportsDepositsIndexRoute
  '/_authenticated/reports/ledger/': typeof AuthenticatedReportsLedgerIndexRoute
  '/_authenticated/reports/sales/': typeof AuthenticatedReportsSalesIndexRoute
  '/_authenticated/users/create/': typeof AuthenticatedUsersCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/adjustments'
    | '/audit'
    | '/deliveries'
    | '/deposits'
    | '/prediction'
    | '/prices'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/spbu'
    | '/tanks'
    | '/users'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/mobile-dashboard'
    | '/'
    | '/prediction/deliveries'
    | '/prediction/demand'
    | '/prediction/sales'
    | '/reports/adjustment'
    | '/reports/attendance'
    | '/reports/deliveries'
    | '/reports/deposits'
    | '/reports/ledger'
    | '/reports/sales'
    | '/users/create'
    | '/deliveries/confirm'
    | '/errors/$error'
    | '/reports/all'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/adjustments/'
    | '/apps'
    | '/audit/'
    | '/chats'
    | '/deliveries/'
    | '/deposits/'
    | '/help-center'
    | '/prediction/'
    | '/prices/'
    | '/reports/'
    | '/sales/'
    | '/settings/'
    | '/spbu/'
    | '/tasks'
    | '/users/'
    | '/deliveries/confirm/'
    | '/prediction/deliveries/'
    | '/prediction/demand/'
    | '/prediction/sales/'
    | '/reports/adjustment/'
    | '/reports/all/'
    | '/reports/attendance/'
    | '/reports/deliveries/'
    | '/reports/deposits/'
    | '/reports/ledger/'
    | '/reports/sales/'
    | '/users/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tanks'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/mobile-dashboard'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/adjustments'
    | '/apps'
    | '/audit'
    | '/chats'
    | '/deliveries'
    | '/deposits'
    | '/help-center'
    | '/prediction'
    | '/prices'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/spbu'
    | '/tasks'
    | '/users'
    | '/deliveries/confirm'
    | '/prediction/deliveries'
    | '/prediction/demand'
    | '/prediction/sales'
    | '/reports/adjustment'
    | '/reports/all'
    | '/reports/attendance'
    | '/reports/deliveries'
    | '/reports/deposits'
    | '/reports/ledger'
    | '/reports/sales'
    | '/users/create'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/adjustments'
    | '/_authenticated/audit'
    | '/_authenticated/deliveries'
    | '/_authenticated/deposits'
    | '/_authenticated/prediction'
    | '/_authenticated/prices'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/spbu'
    | '/_authenticated/tanks'
    | '/_authenticated/users'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/mobile-dashboard'
    | '/_authenticated/'
    | '/_authenticated/prediction/deliveries'
    | '/_authenticated/prediction/demand'
    | '/_authenticated/prediction/sales'
    | '/_authenticated/reports/adjustment'
    | '/_authenticated/reports/attendance'
    | '/_authenticated/reports/deliveries'
    | '/_authenticated/reports/deposits'
    | '/_authenticated/reports/ledger'
    | '/_authenticated/reports/sales'
    | '/_authenticated/users/create'
    | '/_authenticated/deliveries/confirm'
    | '/_authenticated/errors/$error'
    | '/_authenticated/reports/all'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/adjustments/'
    | '/_authenticated/apps/'
    | '/_authenticated/audit/'
    | '/_authenticated/chats/'
    | '/_authenticated/deliveries/'
    | '/_authenticated/deposits/'
    | '/_authenticated/help-center/'
    | '/_authenticated/prediction/'
    | '/_authenticated/prices/'
    | '/_authenticated/reports/'
    | '/_authenticated/sales/'
    | '/_authenticated/settings/'
    | '/_authenticated/spbu/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/deliveries/confirm/'
    | '/_authenticated/prediction/deliveries/'
    | '/_authenticated/prediction/demand/'
    | '/_authenticated/prediction/sales/'
    | '/_authenticated/reports/adjustment/'
    | '/_authenticated/reports/all/'
    | '/_authenticated/reports/attendance/'
    | '/_authenticated/reports/deliveries/'
    | '/_authenticated/reports/deposits/'
    | '/_authenticated/reports/ledger/'
    | '/_authenticated/reports/sales/'
    | '/_authenticated/users/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile-dashboard': {
      id: '/_authenticated/mobile-dashboard'
      path: '/mobile-dashboard'
      fullPath: '/mobile-dashboard'
      preLoaderRoute: typeof AuthenticatedMobileDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tanks': {
      id: '/_authenticated/tanks'
      path: '/tanks'
      fullPath: '/tanks'
      preLoaderRoute: typeof AuthenticatedTanksRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spbu': {
      id: '/_authenticated/spbu'
      path: '/spbu'
      fullPath: '/spbu'
      preLoaderRoute: typeof AuthenticatedSpbuRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prediction': {
      id: '/_authenticated/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof AuthenticatedPredictionRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits': {
      id: '/_authenticated/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthenticatedDepositsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adjustments': {
      id: '/_authenticated/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AuthenticatedAdjustmentsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spbu/': {
      id: '/_authenticated/spbu/'
      path: '/'
      fullPath: '/spbu/'
      preLoaderRoute: typeof AuthenticatedSpbuIndexRouteImport
      parentRoute: typeof AuthenticatedSpbuRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedSalesRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/prices/': {
      id: '/_authenticated/prices/'
      path: '/'
      fullPath: '/prices/'
      preLoaderRoute: typeof AuthenticatedPricesIndexRouteImport
      parentRoute: typeof AuthenticatedPricesRouteRoute
    }
    '/_authenticated/prediction/': {
      id: '/_authenticated/prediction/'
      path: '/'
      fullPath: '/prediction/'
      preLoaderRoute: typeof AuthenticatedPredictionIndexRouteImport
      parentRoute: typeof AuthenticatedPredictionRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits/': {
      id: '/_authenticated/deposits/'
      path: '/'
      fullPath: '/deposits/'
      preLoaderRoute: typeof AuthenticatedDepositsIndexRouteImport
      parentRoute: typeof AuthenticatedDepositsRouteRoute
    }
    '/_authenticated/deliveries/': {
      id: '/_authenticated/deliveries/'
      path: '/'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof AuthenticatedDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedDeliveriesRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedAuditRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adjustments/': {
      id: '/_authenticated/adjustments/'
      path: '/'
      fullPath: '/adjustments/'
      preLoaderRoute: typeof AuthenticatedAdjustmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdjustmentsRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/all': {
      id: '/_authenticated/reports/all'
      path: '/all'
      fullPath: '/reports/all'
      preLoaderRoute: typeof AuthenticatedReportsAllRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries/confirm': {
      id: '/_authenticated/deliveries/confirm'
      path: '/confirm'
      fullPath: '/deliveries/confirm'
      preLoaderRoute: typeof AuthenticatedDeliveriesConfirmRouteImport
      parentRoute: typeof AuthenticatedDeliveriesRouteRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteRouteImport
      parentRoute: typeof AuthenticatedUsersRouteRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/reports/ledger': {
      id: '/_authenticated/reports/ledger'
      path: '/ledger'
      fullPath: '/reports/ledger'
      preLoaderRoute: typeof AuthenticatedReportsLedgerRouteRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/reports/deposits': {
      id: '/_authenticated/reports/deposits'
      path: '/deposits'
      fullPath: '/reports/deposits'
      preLoaderRoute: typeof AuthenticatedReportsDepositsRouteRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/reports/deliveries': {
      id: '/_authenticated/reports/deliveries'
      path: '/deliveries'
      fullPath: '/reports/deliveries'
      preLoaderRoute: typeof AuthenticatedReportsDeliveriesRouteRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/reports/attendance': {
      id: '/_authenticated/reports/attendance'
      path: '/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof AuthenticatedReportsAttendanceRouteRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/reports/adjustment': {
      id: '/_authenticated/reports/adjustment'
      path: '/adjustment'
      fullPath: '/reports/adjustment'
      preLoaderRoute: typeof AuthenticatedReportsAdjustmentRouteRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/prediction/sales': {
      id: '/_authenticated/prediction/sales'
      path: '/sales'
      fullPath: '/prediction/sales'
      preLoaderRoute: typeof AuthenticatedPredictionSalesRouteRouteImport
      parentRoute: typeof AuthenticatedPredictionRouteRoute
    }
    '/_authenticated/prediction/demand': {
      id: '/_authenticated/prediction/demand'
      path: '/demand'
      fullPath: '/prediction/demand'
      preLoaderRoute: typeof AuthenticatedPredictionDemandRouteRouteImport
      parentRoute: typeof AuthenticatedPredictionRouteRoute
    }
    '/_authenticated/prediction/deliveries': {
      id: '/_authenticated/prediction/deliveries'
      path: '/deliveries'
      fullPath: '/prediction/deliveries'
      preLoaderRoute: typeof AuthenticatedPredictionDeliveriesRouteRouteImport
      parentRoute: typeof AuthenticatedPredictionRouteRoute
    }
    '/_authenticated/users/create/': {
      id: '/_authenticated/users/create/'
      path: '/'
      fullPath: '/users/create/'
      preLoaderRoute: typeof AuthenticatedUsersCreateIndexRouteImport
      parentRoute: typeof AuthenticatedUsersCreateRouteRoute
    }
    '/_authenticated/reports/sales/': {
      id: '/_authenticated/reports/sales/'
      path: '/'
      fullPath: '/reports/sales/'
      preLoaderRoute: typeof AuthenticatedReportsSalesIndexRouteImport
      parentRoute: typeof AuthenticatedReportsSalesRouteRoute
    }
    '/_authenticated/reports/ledger/': {
      id: '/_authenticated/reports/ledger/'
      path: '/'
      fullPath: '/reports/ledger/'
      preLoaderRoute: typeof AuthenticatedReportsLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedReportsLedgerRouteRoute
    }
    '/_authenticated/reports/deposits/': {
      id: '/_authenticated/reports/deposits/'
      path: '/'
      fullPath: '/reports/deposits/'
      preLoaderRoute: typeof AuthenticatedReportsDepositsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsDepositsRouteRoute
    }
    '/_authenticated/reports/deliveries/': {
      id: '/_authenticated/reports/deliveries/'
      path: '/'
      fullPath: '/reports/deliveries/'
      preLoaderRoute: typeof AuthenticatedReportsDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedReportsDeliveriesRouteRoute
    }
    '/_authenticated/reports/attendance/': {
      id: '/_authenticated/reports/attendance/'
      path: '/'
      fullPath: '/reports/attendance/'
      preLoaderRoute: typeof AuthenticatedReportsAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedReportsAttendanceRouteRoute
    }
    '/_authenticated/reports/all/': {
      id: '/_authenticated/reports/all/'
      path: '/'
      fullPath: '/reports/all/'
      preLoaderRoute: typeof AuthenticatedReportsAllIndexRouteImport
      parentRoute: typeof AuthenticatedReportsAllRoute
    }
    '/_authenticated/reports/adjustment/': {
      id: '/_authenticated/reports/adjustment/'
      path: '/'
      fullPath: '/reports/adjustment/'
      preLoaderRoute: typeof AuthenticatedReportsAdjustmentIndexRouteImport
      parentRoute: typeof AuthenticatedReportsAdjustmentRouteRoute
    }
    '/_authenticated/prediction/sales/': {
      id: '/_authenticated/prediction/sales/'
      path: '/'
      fullPath: '/prediction/sales/'
      preLoaderRoute: typeof AuthenticatedPredictionSalesIndexRouteImport
      parentRoute: typeof AuthenticatedPredictionSalesRouteRoute
    }
    '/_authenticated/prediction/demand/': {
      id: '/_authenticated/prediction/demand/'
      path: '/'
      fullPath: '/prediction/demand/'
      preLoaderRoute: typeof AuthenticatedPredictionDemandIndexRouteImport
      parentRoute: typeof AuthenticatedPredictionDemandRouteRoute
    }
    '/_authenticated/prediction/deliveries/': {
      id: '/_authenticated/prediction/deliveries/'
      path: '/'
      fullPath: '/prediction/deliveries/'
      preLoaderRoute: typeof AuthenticatedPredictionDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedPredictionDeliveriesRouteRoute
    }
    '/_authenticated/deliveries/confirm/': {
      id: '/_authenticated/deliveries/confirm/'
      path: '/'
      fullPath: '/deliveries/confirm/'
      preLoaderRoute: typeof AuthenticatedDeliveriesConfirmIndexRouteImport
      parentRoute: typeof AuthenticatedDeliveriesConfirmRoute
    }
  }
}

interface AuthenticatedAdjustmentsRouteRouteChildren {
  AuthenticatedAdjustmentsIndexRoute: typeof AuthenticatedAdjustmentsIndexRoute
}

const AuthenticatedAdjustmentsRouteRouteChildren: AuthenticatedAdjustmentsRouteRouteChildren =
  {
    AuthenticatedAdjustmentsIndexRoute: AuthenticatedAdjustmentsIndexRoute,
  }

const AuthenticatedAdjustmentsRouteRouteWithChildren =
  AuthenticatedAdjustmentsRouteRoute._addFileChildren(
    AuthenticatedAdjustmentsRouteRouteChildren,
  )

interface AuthenticatedAuditRouteRouteChildren {
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
}

const AuthenticatedAuditRouteRouteChildren: AuthenticatedAuditRouteRouteChildren =
  {
    AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  }

const AuthenticatedAuditRouteRouteWithChildren =
  AuthenticatedAuditRouteRoute._addFileChildren(
    AuthenticatedAuditRouteRouteChildren,
  )

interface AuthenticatedDeliveriesConfirmRouteChildren {
  AuthenticatedDeliveriesConfirmIndexRoute: typeof AuthenticatedDeliveriesConfirmIndexRoute
}

const AuthenticatedDeliveriesConfirmRouteChildren: AuthenticatedDeliveriesConfirmRouteChildren =
  {
    AuthenticatedDeliveriesConfirmIndexRoute:
      AuthenticatedDeliveriesConfirmIndexRoute,
  }

const AuthenticatedDeliveriesConfirmRouteWithChildren =
  AuthenticatedDeliveriesConfirmRoute._addFileChildren(
    AuthenticatedDeliveriesConfirmRouteChildren,
  )

interface AuthenticatedDeliveriesRouteRouteChildren {
  AuthenticatedDeliveriesConfirmRoute: typeof AuthenticatedDeliveriesConfirmRouteWithChildren
  AuthenticatedDeliveriesIndexRoute: typeof AuthenticatedDeliveriesIndexRoute
}

const AuthenticatedDeliveriesRouteRouteChildren: AuthenticatedDeliveriesRouteRouteChildren =
  {
    AuthenticatedDeliveriesConfirmRoute:
      AuthenticatedDeliveriesConfirmRouteWithChildren,
    AuthenticatedDeliveriesIndexRoute: AuthenticatedDeliveriesIndexRoute,
  }

const AuthenticatedDeliveriesRouteRouteWithChildren =
  AuthenticatedDeliveriesRouteRoute._addFileChildren(
    AuthenticatedDeliveriesRouteRouteChildren,
  )

interface AuthenticatedDepositsRouteRouteChildren {
  AuthenticatedDepositsIndexRoute: typeof AuthenticatedDepositsIndexRoute
}

const AuthenticatedDepositsRouteRouteChildren: AuthenticatedDepositsRouteRouteChildren =
  {
    AuthenticatedDepositsIndexRoute: AuthenticatedDepositsIndexRoute,
  }

const AuthenticatedDepositsRouteRouteWithChildren =
  AuthenticatedDepositsRouteRoute._addFileChildren(
    AuthenticatedDepositsRouteRouteChildren,
  )

interface AuthenticatedPredictionDeliveriesRouteRouteChildren {
  AuthenticatedPredictionDeliveriesIndexRoute: typeof AuthenticatedPredictionDeliveriesIndexRoute
}

const AuthenticatedPredictionDeliveriesRouteRouteChildren: AuthenticatedPredictionDeliveriesRouteRouteChildren =
  {
    AuthenticatedPredictionDeliveriesIndexRoute:
      AuthenticatedPredictionDeliveriesIndexRoute,
  }

const AuthenticatedPredictionDeliveriesRouteRouteWithChildren =
  AuthenticatedPredictionDeliveriesRouteRoute._addFileChildren(
    AuthenticatedPredictionDeliveriesRouteRouteChildren,
  )

interface AuthenticatedPredictionDemandRouteRouteChildren {
  AuthenticatedPredictionDemandIndexRoute: typeof AuthenticatedPredictionDemandIndexRoute
}

const AuthenticatedPredictionDemandRouteRouteChildren: AuthenticatedPredictionDemandRouteRouteChildren =
  {
    AuthenticatedPredictionDemandIndexRoute:
      AuthenticatedPredictionDemandIndexRoute,
  }

const AuthenticatedPredictionDemandRouteRouteWithChildren =
  AuthenticatedPredictionDemandRouteRoute._addFileChildren(
    AuthenticatedPredictionDemandRouteRouteChildren,
  )

interface AuthenticatedPredictionSalesRouteRouteChildren {
  AuthenticatedPredictionSalesIndexRoute: typeof AuthenticatedPredictionSalesIndexRoute
}

const AuthenticatedPredictionSalesRouteRouteChildren: AuthenticatedPredictionSalesRouteRouteChildren =
  {
    AuthenticatedPredictionSalesIndexRoute:
      AuthenticatedPredictionSalesIndexRoute,
  }

const AuthenticatedPredictionSalesRouteRouteWithChildren =
  AuthenticatedPredictionSalesRouteRoute._addFileChildren(
    AuthenticatedPredictionSalesRouteRouteChildren,
  )

interface AuthenticatedPredictionRouteRouteChildren {
  AuthenticatedPredictionDeliveriesRouteRoute: typeof AuthenticatedPredictionDeliveriesRouteRouteWithChildren
  AuthenticatedPredictionDemandRouteRoute: typeof AuthenticatedPredictionDemandRouteRouteWithChildren
  AuthenticatedPredictionSalesRouteRoute: typeof AuthenticatedPredictionSalesRouteRouteWithChildren
  AuthenticatedPredictionIndexRoute: typeof AuthenticatedPredictionIndexRoute
}

const AuthenticatedPredictionRouteRouteChildren: AuthenticatedPredictionRouteRouteChildren =
  {
    AuthenticatedPredictionDeliveriesRouteRoute:
      AuthenticatedPredictionDeliveriesRouteRouteWithChildren,
    AuthenticatedPredictionDemandRouteRoute:
      AuthenticatedPredictionDemandRouteRouteWithChildren,
    AuthenticatedPredictionSalesRouteRoute:
      AuthenticatedPredictionSalesRouteRouteWithChildren,
    AuthenticatedPredictionIndexRoute: AuthenticatedPredictionIndexRoute,
  }

const AuthenticatedPredictionRouteRouteWithChildren =
  AuthenticatedPredictionRouteRoute._addFileChildren(
    AuthenticatedPredictionRouteRouteChildren,
  )

interface AuthenticatedPricesRouteRouteChildren {
  AuthenticatedPricesIndexRoute: typeof AuthenticatedPricesIndexRoute
}

const AuthenticatedPricesRouteRouteChildren: AuthenticatedPricesRouteRouteChildren =
  {
    AuthenticatedPricesIndexRoute: AuthenticatedPricesIndexRoute,
  }

const AuthenticatedPricesRouteRouteWithChildren =
  AuthenticatedPricesRouteRoute._addFileChildren(
    AuthenticatedPricesRouteRouteChildren,
  )

interface AuthenticatedReportsAdjustmentRouteRouteChildren {
  AuthenticatedReportsAdjustmentIndexRoute: typeof AuthenticatedReportsAdjustmentIndexRoute
}

const AuthenticatedReportsAdjustmentRouteRouteChildren: AuthenticatedReportsAdjustmentRouteRouteChildren =
  {
    AuthenticatedReportsAdjustmentIndexRoute:
      AuthenticatedReportsAdjustmentIndexRoute,
  }

const AuthenticatedReportsAdjustmentRouteRouteWithChildren =
  AuthenticatedReportsAdjustmentRouteRoute._addFileChildren(
    AuthenticatedReportsAdjustmentRouteRouteChildren,
  )

interface AuthenticatedReportsAttendanceRouteRouteChildren {
  AuthenticatedReportsAttendanceIndexRoute: typeof AuthenticatedReportsAttendanceIndexRoute
}

const AuthenticatedReportsAttendanceRouteRouteChildren: AuthenticatedReportsAttendanceRouteRouteChildren =
  {
    AuthenticatedReportsAttendanceIndexRoute:
      AuthenticatedReportsAttendanceIndexRoute,
  }

const AuthenticatedReportsAttendanceRouteRouteWithChildren =
  AuthenticatedReportsAttendanceRouteRoute._addFileChildren(
    AuthenticatedReportsAttendanceRouteRouteChildren,
  )

interface AuthenticatedReportsDeliveriesRouteRouteChildren {
  AuthenticatedReportsDeliveriesIndexRoute: typeof AuthenticatedReportsDeliveriesIndexRoute
}

const AuthenticatedReportsDeliveriesRouteRouteChildren: AuthenticatedReportsDeliveriesRouteRouteChildren =
  {
    AuthenticatedReportsDeliveriesIndexRoute:
      AuthenticatedReportsDeliveriesIndexRoute,
  }

const AuthenticatedReportsDeliveriesRouteRouteWithChildren =
  AuthenticatedReportsDeliveriesRouteRoute._addFileChildren(
    AuthenticatedReportsDeliveriesRouteRouteChildren,
  )

interface AuthenticatedReportsDepositsRouteRouteChildren {
  AuthenticatedReportsDepositsIndexRoute: typeof AuthenticatedReportsDepositsIndexRoute
}

const AuthenticatedReportsDepositsRouteRouteChildren: AuthenticatedReportsDepositsRouteRouteChildren =
  {
    AuthenticatedReportsDepositsIndexRoute:
      AuthenticatedReportsDepositsIndexRoute,
  }

const AuthenticatedReportsDepositsRouteRouteWithChildren =
  AuthenticatedReportsDepositsRouteRoute._addFileChildren(
    AuthenticatedReportsDepositsRouteRouteChildren,
  )

interface AuthenticatedReportsLedgerRouteRouteChildren {
  AuthenticatedReportsLedgerIndexRoute: typeof AuthenticatedReportsLedgerIndexRoute
}

const AuthenticatedReportsLedgerRouteRouteChildren: AuthenticatedReportsLedgerRouteRouteChildren =
  {
    AuthenticatedReportsLedgerIndexRoute: AuthenticatedReportsLedgerIndexRoute,
  }

const AuthenticatedReportsLedgerRouteRouteWithChildren =
  AuthenticatedReportsLedgerRouteRoute._addFileChildren(
    AuthenticatedReportsLedgerRouteRouteChildren,
  )

interface AuthenticatedReportsSalesRouteRouteChildren {
  AuthenticatedReportsSalesIndexRoute: typeof AuthenticatedReportsSalesIndexRoute
}

const AuthenticatedReportsSalesRouteRouteChildren: AuthenticatedReportsSalesRouteRouteChildren =
  {
    AuthenticatedReportsSalesIndexRoute: AuthenticatedReportsSalesIndexRoute,
  }

const AuthenticatedReportsSalesRouteRouteWithChildren =
  AuthenticatedReportsSalesRouteRoute._addFileChildren(
    AuthenticatedReportsSalesRouteRouteChildren,
  )

interface AuthenticatedReportsAllRouteChildren {
  AuthenticatedReportsAllIndexRoute: typeof AuthenticatedReportsAllIndexRoute
}

const AuthenticatedReportsAllRouteChildren: AuthenticatedReportsAllRouteChildren =
  {
    AuthenticatedReportsAllIndexRoute: AuthenticatedReportsAllIndexRoute,
  }

const AuthenticatedReportsAllRouteWithChildren =
  AuthenticatedReportsAllRoute._addFileChildren(
    AuthenticatedReportsAllRouteChildren,
  )

interface AuthenticatedReportsRouteRouteChildren {
  AuthenticatedReportsAdjustmentRouteRoute: typeof AuthenticatedReportsAdjustmentRouteRouteWithChildren
  AuthenticatedReportsAttendanceRouteRoute: typeof AuthenticatedReportsAttendanceRouteRouteWithChildren
  AuthenticatedReportsDeliveriesRouteRoute: typeof AuthenticatedReportsDeliveriesRouteRouteWithChildren
  AuthenticatedReportsDepositsRouteRoute: typeof AuthenticatedReportsDepositsRouteRouteWithChildren
  AuthenticatedReportsLedgerRouteRoute: typeof AuthenticatedReportsLedgerRouteRouteWithChildren
  AuthenticatedReportsSalesRouteRoute: typeof AuthenticatedReportsSalesRouteRouteWithChildren
  AuthenticatedReportsAllRoute: typeof AuthenticatedReportsAllRouteWithChildren
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteRouteChildren: AuthenticatedReportsRouteRouteChildren =
  {
    AuthenticatedReportsAdjustmentRouteRoute:
      AuthenticatedReportsAdjustmentRouteRouteWithChildren,
    AuthenticatedReportsAttendanceRouteRoute:
      AuthenticatedReportsAttendanceRouteRouteWithChildren,
    AuthenticatedReportsDeliveriesRouteRoute:
      AuthenticatedReportsDeliveriesRouteRouteWithChildren,
    AuthenticatedReportsDepositsRouteRoute:
      AuthenticatedReportsDepositsRouteRouteWithChildren,
    AuthenticatedReportsLedgerRouteRoute:
      AuthenticatedReportsLedgerRouteRouteWithChildren,
    AuthenticatedReportsSalesRouteRoute:
      AuthenticatedReportsSalesRouteRouteWithChildren,
    AuthenticatedReportsAllRoute: AuthenticatedReportsAllRouteWithChildren,
    AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  }

const AuthenticatedReportsRouteRouteWithChildren =
  AuthenticatedReportsRouteRoute._addFileChildren(
    AuthenticatedReportsRouteRouteChildren,
  )

interface AuthenticatedSalesRouteRouteChildren {
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedSalesRouteRouteChildren: AuthenticatedSalesRouteRouteChildren =
  {
    AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  }

const AuthenticatedSalesRouteRouteWithChildren =
  AuthenticatedSalesRouteRoute._addFileChildren(
    AuthenticatedSalesRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSpbuRouteRouteChildren {
  AuthenticatedSpbuIndexRoute: typeof AuthenticatedSpbuIndexRoute
}

const AuthenticatedSpbuRouteRouteChildren: AuthenticatedSpbuRouteRouteChildren =
  {
    AuthenticatedSpbuIndexRoute: AuthenticatedSpbuIndexRoute,
  }

const AuthenticatedSpbuRouteRouteWithChildren =
  AuthenticatedSpbuRouteRoute._addFileChildren(
    AuthenticatedSpbuRouteRouteChildren,
  )

interface AuthenticatedUsersCreateRouteRouteChildren {
  AuthenticatedUsersCreateIndexRoute: typeof AuthenticatedUsersCreateIndexRoute
}

const AuthenticatedUsersCreateRouteRouteChildren: AuthenticatedUsersCreateRouteRouteChildren =
  {
    AuthenticatedUsersCreateIndexRoute: AuthenticatedUsersCreateIndexRoute,
  }

const AuthenticatedUsersCreateRouteRouteWithChildren =
  AuthenticatedUsersCreateRouteRoute._addFileChildren(
    AuthenticatedUsersCreateRouteRouteChildren,
  )

interface AuthenticatedUsersRouteRouteChildren {
  AuthenticatedUsersCreateRouteRoute: typeof AuthenticatedUsersCreateRouteRouteWithChildren
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteRouteChildren: AuthenticatedUsersRouteRouteChildren =
  {
    AuthenticatedUsersCreateRouteRoute:
      AuthenticatedUsersCreateRouteRouteWithChildren,
    AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  }

const AuthenticatedUsersRouteRouteWithChildren =
  AuthenticatedUsersRouteRoute._addFileChildren(
    AuthenticatedUsersRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdjustmentsRouteRoute: typeof AuthenticatedAdjustmentsRouteRouteWithChildren
  AuthenticatedAuditRouteRoute: typeof AuthenticatedAuditRouteRouteWithChildren
  AuthenticatedDeliveriesRouteRoute: typeof AuthenticatedDeliveriesRouteRouteWithChildren
  AuthenticatedDepositsRouteRoute: typeof AuthenticatedDepositsRouteRouteWithChildren
  AuthenticatedPredictionRouteRoute: typeof AuthenticatedPredictionRouteRouteWithChildren
  AuthenticatedPricesRouteRoute: typeof AuthenticatedPricesRouteRouteWithChildren
  AuthenticatedReportsRouteRoute: typeof AuthenticatedReportsRouteRouteWithChildren
  AuthenticatedSalesRouteRoute: typeof AuthenticatedSalesRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSpbuRouteRoute: typeof AuthenticatedSpbuRouteRouteWithChildren
  AuthenticatedTanksRouteRoute: typeof AuthenticatedTanksRouteRoute
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRouteWithChildren
  AuthenticatedMobileDashboardRoute: typeof AuthenticatedMobileDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdjustmentsRouteRoute:
    AuthenticatedAdjustmentsRouteRouteWithChildren,
  AuthenticatedAuditRouteRoute: AuthenticatedAuditRouteRouteWithChildren,
  AuthenticatedDeliveriesRouteRoute:
    AuthenticatedDeliveriesRouteRouteWithChildren,
  AuthenticatedDepositsRouteRoute: AuthenticatedDepositsRouteRouteWithChildren,
  AuthenticatedPredictionRouteRoute:
    AuthenticatedPredictionRouteRouteWithChildren,
  AuthenticatedPricesRouteRoute: AuthenticatedPricesRouteRouteWithChildren,
  AuthenticatedReportsRouteRoute: AuthenticatedReportsRouteRouteWithChildren,
  AuthenticatedSalesRouteRoute: AuthenticatedSalesRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSpbuRouteRoute: AuthenticatedSpbuRouteRouteWithChildren,
  AuthenticatedTanksRouteRoute: AuthenticatedTanksRouteRoute,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRouteWithChildren,
  AuthenticatedMobileDashboardRoute: AuthenticatedMobileDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
